
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.3 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xvtc.h"

/*
* The configuration table for devices
*/

XVtc_Config XVtc_ConfigTable[] =
{
	{
		XPAR_FMC_IMAGEON_HDMIO_RGB_V_TC_0_DEVICE_ID,
		XPAR_FMC_IMAGEON_HDMIO_RGB_V_TC_0_BASEADDR
	}
};


