// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_filter_sobel_filter_core (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src_data_stream_0_V_dout,
        src_data_stream_0_V_empty_n,
        src_data_stream_0_V_read,
        src_data_stream_1_V_dout,
        src_data_stream_1_V_empty_n,
        src_data_stream_1_V_read,
        dst_data_stream_0_V_din,
        dst_data_stream_0_V_full_n,
        dst_data_stream_0_V_write,
        dst_data_stream_1_V_din,
        dst_data_stream_1_V_full_n,
        dst_data_stream_1_V_write,
        rows_dout,
        rows_empty_n,
        rows_read,
        cols_dout,
        cols_empty_n,
        cols_read,
        C_XR0C0_dout,
        C_XR0C0_empty_n,
        C_XR0C0_read,
        C_XR0C1_dout,
        C_XR0C1_empty_n,
        C_XR0C1_read,
        C_XR0C2_dout,
        C_XR0C2_empty_n,
        C_XR0C2_read,
        C_XR1C0_dout,
        C_XR1C0_empty_n,
        C_XR1C0_read,
        C_XR1C1_dout,
        C_XR1C1_empty_n,
        C_XR1C1_read,
        C_XR1C2_dout,
        C_XR1C2_empty_n,
        C_XR1C2_read,
        C_XR2C0_dout,
        C_XR2C0_empty_n,
        C_XR2C0_read,
        C_XR2C1_dout,
        C_XR2C1_empty_n,
        C_XR2C1_read,
        C_XR2C2_dout,
        C_XR2C2_empty_n,
        C_XR2C2_read,
        C_YR0C0_dout,
        C_YR0C0_empty_n,
        C_YR0C0_read,
        C_YR0C1_dout,
        C_YR0C1_empty_n,
        C_YR0C1_read,
        C_YR0C2_dout,
        C_YR0C2_empty_n,
        C_YR0C2_read,
        C_YR1C0_dout,
        C_YR1C0_empty_n,
        C_YR1C0_read,
        C_YR1C1_dout,
        C_YR1C1_empty_n,
        C_YR1C1_read,
        C_YR1C2_dout,
        C_YR1C2_empty_n,
        C_YR1C2_read,
        C_YR2C0_dout,
        C_YR2C0_empty_n,
        C_YR2C0_read,
        C_YR2C1_dout,
        C_YR2C1_empty_n,
        C_YR2C1_read,
        c_high_thresh_dout,
        c_high_thresh_empty_n,
        c_high_thresh_read,
        c_low_thresh_dout,
        c_low_thresh_empty_n,
        c_low_thresh_read,
        c_invert_dout,
        c_invert_empty_n,
        c_invert_read
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_st2_fsm_1 = 4'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 4'b100;
parameter    ap_ST_st18_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv8_80 = 8'b10000000;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv16_FF = 16'b11111111;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] src_data_stream_0_V_dout;
input   src_data_stream_0_V_empty_n;
output   src_data_stream_0_V_read;
input  [7:0] src_data_stream_1_V_dout;
input   src_data_stream_1_V_empty_n;
output   src_data_stream_1_V_read;
output  [7:0] dst_data_stream_0_V_din;
input   dst_data_stream_0_V_full_n;
output   dst_data_stream_0_V_write;
output  [7:0] dst_data_stream_1_V_din;
input   dst_data_stream_1_V_full_n;
output   dst_data_stream_1_V_write;
input  [31:0] rows_dout;
input   rows_empty_n;
output   rows_read;
input  [31:0] cols_dout;
input   cols_empty_n;
output   cols_read;
input  [31:0] C_XR0C0_dout;
input   C_XR0C0_empty_n;
output   C_XR0C0_read;
input  [31:0] C_XR0C1_dout;
input   C_XR0C1_empty_n;
output   C_XR0C1_read;
input  [31:0] C_XR0C2_dout;
input   C_XR0C2_empty_n;
output   C_XR0C2_read;
input  [31:0] C_XR1C0_dout;
input   C_XR1C0_empty_n;
output   C_XR1C0_read;
input  [31:0] C_XR1C1_dout;
input   C_XR1C1_empty_n;
output   C_XR1C1_read;
input  [31:0] C_XR1C2_dout;
input   C_XR1C2_empty_n;
output   C_XR1C2_read;
input  [31:0] C_XR2C0_dout;
input   C_XR2C0_empty_n;
output   C_XR2C0_read;
input  [31:0] C_XR2C1_dout;
input   C_XR2C1_empty_n;
output   C_XR2C1_read;
input  [31:0] C_XR2C2_dout;
input   C_XR2C2_empty_n;
output   C_XR2C2_read;
input  [31:0] C_YR0C0_dout;
input   C_YR0C0_empty_n;
output   C_YR0C0_read;
input  [31:0] C_YR0C1_dout;
input   C_YR0C1_empty_n;
output   C_YR0C1_read;
input  [31:0] C_YR0C2_dout;
input   C_YR0C2_empty_n;
output   C_YR0C2_read;
input  [31:0] C_YR1C0_dout;
input   C_YR1C0_empty_n;
output   C_YR1C0_read;
input  [31:0] C_YR1C1_dout;
input   C_YR1C1_empty_n;
output   C_YR1C1_read;
input  [31:0] C_YR1C2_dout;
input   C_YR1C2_empty_n;
output   C_YR1C2_read;
input  [31:0] C_YR2C0_dout;
input   C_YR2C0_empty_n;
output   C_YR2C0_read;
input  [31:0] C_YR2C1_dout;
input   C_YR2C1_empty_n;
output   C_YR2C1_read;
input  [31:0] c_high_thresh_dout;
input   c_high_thresh_empty_n;
output   c_high_thresh_read;
input  [31:0] c_low_thresh_dout;
input   c_low_thresh_empty_n;
output   c_low_thresh_read;
input  [31:0] c_invert_dout;
input   c_invert_empty_n;
output   c_invert_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg src_data_stream_0_V_read;
reg src_data_stream_1_V_read;
reg dst_data_stream_0_V_write;
reg dst_data_stream_1_V_write;
reg rows_read;
reg cols_read;
reg C_XR0C0_read;
reg C_XR0C1_read;
reg C_XR0C2_read;
reg C_XR1C0_read;
reg C_XR1C1_read;
reg C_XR1C2_read;
reg C_XR2C0_read;
reg C_XR2C1_read;
reg C_XR2C2_read;
reg C_YR0C0_read;
reg C_YR0C1_read;
reg C_YR0C2_read;
reg C_YR1C0_read;
reg C_YR1C1_read;
reg C_YR1C2_read;
reg C_YR2C0_read;
reg C_YR2C1_read;
reg c_high_thresh_read;
reg c_low_thresh_read;
reg c_invert_read;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm = 4'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_23;
reg   [11:0] col_assign_reg_395;
reg   [11:0] ap_reg_ppstg_col_assign_reg_395_pp0_it1;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_bdd_142;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg   [0:0] exitcond_reg_1324;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1324_pp0_it2;
reg   [0:0] or_cond_i_i_reg_1356;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it2;
reg    ap_sig_bdd_164;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg    ap_reg_ppiten_pp0_it8 = 1'b0;
reg    ap_reg_ppiten_pp0_it9 = 1'b0;
reg    ap_reg_ppiten_pp0_it10 = 1'b0;
reg    ap_reg_ppiten_pp0_it11 = 1'b0;
reg    ap_reg_ppiten_pp0_it12 = 1'b0;
reg    ap_reg_ppiten_pp0_it13 = 1'b0;
reg   [0:0] or_cond3_i_i_reg_1360;
reg   [0:0] ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it13;
reg    ap_sig_bdd_197;
reg    ap_reg_ppiten_pp0_it14 = 1'b0;
reg   [11:0] ap_reg_ppstg_col_assign_reg_395_pp0_it2;
reg   [31:0] c_high_thresh_read_reg_1165;
reg    ap_sig_bdd_254;
reg   [31:0] c_low_thresh_read_reg_1170;
wire   [11:0] rows_cast_i_i_cast_fu_415_p1;
reg   [11:0] rows_cast_i_i_cast_reg_1175;
wire  signed [12:0] tmp_29_i_i_cast_fu_425_p1;
reg  signed [12:0] tmp_29_i_i_cast_reg_1180;
wire   [11:0] cols_cast_i_i_cast_fu_429_p1;
reg   [11:0] cols_cast_i_i_cast_reg_1185;
wire  signed [12:0] tmp_30_i_i_cast_fu_439_p1;
reg  signed [12:0] tmp_30_i_i_cast_reg_1190;
wire   [11:0] tmp_3_fu_443_p2;
reg   [11:0] tmp_3_reg_1195;
wire   [11:0] tmp_6_fu_449_p2;
reg   [11:0] tmp_6_reg_1200;
wire  signed [15:0] tmp_36_0_i_i_i_fu_523_p1;
reg  signed [15:0] tmp_36_0_i_i_i_reg_1205;
wire  signed [15:0] tmp_38_0_i_i_i_fu_527_p1;
reg  signed [15:0] tmp_38_0_i_i_i_reg_1210;
wire  signed [15:0] tmp_36_0_1_i_i_i_fu_531_p1;
reg  signed [15:0] tmp_36_0_1_i_i_i_reg_1215;
wire  signed [15:0] tmp_38_0_1_i_i_i_fu_535_p1;
reg  signed [15:0] tmp_38_0_1_i_i_i_reg_1220;
wire  signed [15:0] tmp_36_0_2_i_i_i_fu_539_p1;
reg  signed [15:0] tmp_36_0_2_i_i_i_reg_1225;
wire  signed [15:0] tmp_38_0_2_i_i_i_fu_543_p1;
reg  signed [15:0] tmp_38_0_2_i_i_i_reg_1230;
wire  signed [15:0] tmp_36_1_i_i_i_fu_547_p1;
reg  signed [15:0] tmp_36_1_i_i_i_reg_1235;
wire  signed [15:0] tmp_38_1_i_i_i_fu_551_p1;
reg  signed [15:0] tmp_38_1_i_i_i_reg_1240;
wire  signed [15:0] tmp_36_1_1_i_i_i_fu_555_p1;
reg  signed [15:0] tmp_36_1_1_i_i_i_reg_1245;
wire  signed [15:0] tmp_38_1_1_i_i_i_fu_559_p1;
reg  signed [15:0] tmp_38_1_1_i_i_i_reg_1250;
wire  signed [15:0] tmp_36_1_2_i_i_i_fu_563_p1;
reg  signed [15:0] tmp_36_1_2_i_i_i_reg_1255;
wire  signed [15:0] tmp_38_1_2_i_i_i_fu_567_p1;
reg  signed [15:0] tmp_38_1_2_i_i_i_reg_1260;
wire  signed [15:0] tmp_36_2_i_i_i_fu_571_p1;
reg  signed [15:0] tmp_36_2_i_i_i_reg_1265;
wire  signed [15:0] tmp_38_2_i_i_i_fu_575_p1;
reg  signed [15:0] tmp_38_2_i_i_i_reg_1270;
wire  signed [15:0] tmp_36_2_1_i_i_i_fu_579_p1;
reg  signed [15:0] tmp_36_2_1_i_i_i_reg_1275;
wire  signed [15:0] tmp_38_2_1_i_i_i_fu_583_p1;
reg  signed [15:0] tmp_38_2_1_i_i_i_reg_1280;
wire  signed [15:0] tmp_36_2_2_i_i_i_fu_587_p1;
reg  signed [15:0] tmp_36_2_2_i_i_i_reg_1285;
wire   [0:0] tmp_28_i_i_i_fu_591_p2;
reg   [0:0] tmp_28_i_i_i_reg_1290;
wire   [0:0] exitcond1_fu_601_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_314;
wire   [11:0] row_fu_606_p2;
reg   [11:0] row_reg_1299;
wire   [0:0] tmp_32_i_i_fu_612_p2;
reg   [0:0] tmp_32_i_i_reg_1304;
wire   [0:0] icmp_fu_627_p2;
reg   [0:0] icmp_reg_1309;
wire   [0:0] tmp_34_i_i_fu_633_p2;
reg   [0:0] tmp_34_i_i_reg_1314;
wire   [0:0] tmp_35_i_i_fu_639_p2;
reg   [0:0] tmp_35_i_i_reg_1319;
wire   [0:0] exitcond_fu_644_p2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1324_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1324_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1324_pp0_it4;
wire   [11:0] col_fu_649_p2;
reg   [11:0] col_reg_1328;
wire   [0:0] tmp_37_i_i_fu_655_p2;
reg   [0:0] tmp_37_i_i_reg_1333;
reg   [0:0] ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it3;
wire   [63:0] tmp_38_i_i_fu_660_p1;
reg   [63:0] tmp_38_i_i_reg_1340;
reg   [63:0] ap_reg_ppstg_tmp_38_i_i_reg_1340_pp0_it1;
reg   [10:0] buff_A_val_1_addr_reg_1345;
reg   [10:0] ap_reg_ppstg_buff_A_val_1_addr_reg_1345_pp0_it1;
wire   [0:0] or_cond_i_i_fu_666_p2;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it1;
wire   [0:0] or_cond3_i_i_fu_677_p2;
reg   [0:0] ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it5;
reg   [0:0] ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it6;
reg   [0:0] ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it7;
reg   [0:0] ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it8;
reg   [0:0] ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it9;
reg   [0:0] ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it10;
reg   [0:0] ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it11;
reg   [0:0] ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it12;
wire   [7:0] buff_A_val_1_q0;
reg   [7:0] buff_A_val_1_load_reg_1364;
wire   [7:0] buff_A_val_0_q0;
reg   [7:0] temp_reg_1369;
reg   [7:0] buff_C_val_1_0_1_load_reg_1375;
wire   [0:0] tmp_fu_729_p2;
reg   [0:0] tmp_reg_1385;
wire   [0:0] tmp1_fu_734_p2;
reg   [0:0] tmp1_reg_1390;
reg   [7:0] buff_C_val_2_1_reg_1395;
reg   [7:0] buff_C_val_0_0_i_i_load_1_reg_1401;
reg   [7:0] buff_C_val_1_0_i_i_load_1_reg_1406;
wire   [7:0] buff_C_val_2_0_fu_751_p3;
reg   [7:0] buff_C_val_2_0_reg_1411;
wire   [7:0] buff_C_val_1_0_fu_758_p3;
reg   [7:0] buff_C_val_1_0_reg_1416;
wire   [7:0] buff_C_val_0_0_fu_764_p3;
reg   [7:0] buff_C_val_0_0_reg_1421;
wire   [0:0] or_cond4_i_i_fu_771_p2;
reg   [0:0] or_cond4_i_i_reg_1426;
reg   [0:0] ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it5;
reg   [0:0] ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it6;
reg   [0:0] ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it7;
reg   [0:0] ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it8;
reg   [0:0] ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it9;
reg   [0:0] ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it10;
reg   [0:0] ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it11;
reg   [0:0] ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it12;
reg   [0:0] ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it13;
reg   [7:0] buff_C_val_0_0_i_i_load_reg_1431;
reg   [7:0] buff_C_val_1_0_i_i_load_reg_1436;
wire   [15:0] tmp_35_0_i_i_i_fu_805_p1;
wire   [15:0] tmp_35_0_1_i_i_i_fu_818_p1;
wire   [15:0] tmp_35_0_2_i_i_i_fu_831_p1;
wire   [15:0] tmp_35_1_i_i_i_fu_845_p1;
wire   [15:0] tmp_35_1_1_i_i_i_fu_858_p1;
wire   [15:0] tmp_35_1_2_i_i_i_fu_871_p1;
wire   [15:0] tmp_35_2_i_i_i_fu_885_p1;
wire   [15:0] tmp_35_2_1_i_i_i_fu_898_p1;
wire   [15:0] grp_fu_808_p2;
reg   [15:0] tmp_37_0_i_i_i_reg_1494;
wire   [15:0] grp_fu_813_p2;
reg   [15:0] tmp_39_0_i_i_i_reg_1499;
wire   [15:0] grp_fu_821_p2;
reg   [15:0] tmp_37_0_1_i_i_i_reg_1504;
wire   [15:0] grp_fu_826_p2;
reg   [15:0] tmp_39_0_1_i_i_i_reg_1509;
wire   [15:0] grp_fu_835_p2;
reg   [15:0] tmp_37_0_2_i_i_i_reg_1514;
wire   [15:0] grp_fu_840_p2;
reg   [15:0] tmp_39_0_2_i_i_i_reg_1519;
wire   [15:0] grp_fu_848_p2;
reg   [15:0] tmp_37_1_i_i_i_reg_1524;
wire   [15:0] grp_fu_853_p2;
reg   [15:0] tmp_39_1_i_i_i_reg_1529;
wire   [15:0] grp_fu_861_p2;
reg   [15:0] tmp_37_1_1_i_i_i_reg_1534;
wire   [15:0] grp_fu_866_p2;
reg   [15:0] tmp_39_1_1_i_i_i_reg_1539;
wire   [15:0] grp_fu_875_p2;
reg   [15:0] tmp_37_1_2_i_i_i_reg_1544;
wire   [15:0] grp_fu_880_p2;
reg   [15:0] tmp_39_1_2_i_i_i_reg_1549;
wire   [15:0] grp_fu_888_p2;
reg   [15:0] tmp_37_2_i_i_i_reg_1554;
wire   [15:0] grp_fu_893_p2;
reg   [15:0] tmp_39_2_i_i_i_reg_1559;
wire   [15:0] grp_fu_901_p2;
reg   [15:0] tmp_37_2_1_i_i_i_reg_1564;
wire   [15:0] grp_fu_906_p2;
reg   [15:0] tmp_39_2_1_i_i_i_reg_1569;
wire   [15:0] grp_fu_915_p2;
reg   [15:0] tmp_37_2_2_i_i_i_reg_1574;
wire   [15:0] tmp4_fu_940_p2;
reg   [15:0] tmp4_reg_1580;
wire   [15:0] tmp5_fu_946_p2;
reg   [15:0] tmp5_reg_1585;
wire   [15:0] tmp7_fu_954_p2;
reg   [15:0] tmp7_reg_1590;
wire   [15:0] tmp11_fu_967_p2;
reg   [15:0] tmp11_reg_1595;
wire   [15:0] tmp12_fu_973_p2;
reg   [15:0] tmp12_reg_1600;
wire   [15:0] tmp14_fu_981_p2;
reg   [15:0] tmp14_reg_1605;
wire   [15:0] x_weight_2_2_2_i_i_i_fu_990_p2;
reg   [15:0] x_weight_2_2_2_i_i_i_reg_1610;
wire   [15:0] y_weight_2_2_2_i_i_i_fu_999_p2;
reg   [15:0] y_weight_2_2_2_i_i_i_reg_1617;
wire   [15:0] tmp_19_i_i_i_fu_1014_p3;
reg   [15:0] tmp_19_i_i_i_reg_1624;
wire   [15:0] tmp_22_i_i_i_fu_1031_p3;
reg   [15:0] tmp_22_i_i_i_reg_1629;
wire   [0:0] tmp_23_i_i_i_fu_1042_p2;
reg   [0:0] tmp_23_i_i_i_reg_1634;
wire   [7:0] edge_val_fu_1052_p2;
reg   [7:0] edge_val_reg_1639;
wire   [7:0] edge_val1_i_i_i_fu_1058_p3;
reg   [7:0] edge_val1_i_i_i_reg_1644;
wire   [0:0] tmp_26_i_i_i_fu_1068_p2;
reg   [0:0] tmp_26_i_i_i_reg_1649;
wire   [0:0] tmp_27_i_i_i_fu_1073_p2;
reg   [0:0] tmp_27_i_i_i_reg_1655;
wire   [7:0] edge_val_2_i_i_i_fu_1089_p3;
reg   [7:0] edge_val_2_i_i_i_reg_1660;
wire   [7:0] edge_val_1_fu_1096_p2;
reg   [7:0] edge_val_1_reg_1665;
wire   [10:0] buff_A_val_0_address0;
reg    buff_A_val_0_ce0;
wire   [10:0] buff_A_val_0_address1;
reg    buff_A_val_0_ce1;
reg    buff_A_val_0_we1;
wire   [7:0] buff_A_val_0_d1;
wire   [10:0] buff_A_val_1_address0;
reg    buff_A_val_1_ce0;
wire   [10:0] buff_A_val_1_address1;
reg    buff_A_val_1_ce1;
reg    buff_A_val_1_we1;
wire   [7:0] buff_A_val_1_d1;
wire   [10:0] buff_A_val_2_address0;
reg    buff_A_val_2_ce0;
reg    buff_A_val_2_we0;
wire   [7:0] buff_A_val_2_d0;
wire   [10:0] buff_A_val_2_address1;
reg    buff_A_val_2_ce1;
wire   [7:0] buff_A_val_2_q1;
reg   [11:0] row_i_i_reg_384;
reg    ap_sig_cseq_ST_st18_fsm_3;
reg    ap_sig_bdd_609;
reg   [11:0] col_assign_phi_fu_399_p4;
wire   [63:0] tmp_39_i_i_fu_690_p1;
wire   [63:0] tmp_40_i_i_fu_703_p1;
reg   [7:0] buff_C_val_1_0_1_fu_124;
reg   [7:0] buff_C_val_0_0_i_i_fu_128;
reg   [7:0] buff_C_val_0_1_i_i_fu_132;
reg   [7:0] buff_C_val_0_0_1_fu_136;
reg   [7:0] buff_C_val_1_0_i_i_fu_140;
reg   [7:0] buff_C_val_1_1_i_i_fu_144;
reg   [7:0] buff_C_val_2_1_i_i_fu_148;
reg   [7:0] buff_C_val_2_0_i_i_fu_152;
wire   [10:0] tmp_1_fu_407_p1;
wire   [11:0] tmp_29_i_i_fu_419_p2;
wire   [10:0] tmp_2_fu_411_p1;
wire   [11:0] tmp_30_i_i_fu_433_p2;
wire   [7:0] tmp_4_fu_455_p1;
wire   [7:0] tmp_15_fu_491_p1;
wire   [7:0] tmp_5_fu_459_p1;
wire   [7:0] tmp_16_fu_495_p1;
wire   [7:0] tmp_7_fu_463_p1;
wire   [7:0] tmp_17_fu_499_p1;
wire   [7:0] tmp_8_fu_467_p1;
wire   [7:0] tmp_18_fu_503_p1;
wire   [7:0] tmp_10_fu_471_p1;
wire   [7:0] tmp_19_fu_507_p1;
wire   [7:0] tmp_11_fu_475_p1;
wire   [7:0] tmp_20_fu_511_p1;
wire   [7:0] tmp_12_fu_479_p1;
wire   [7:0] tmp_21_fu_515_p1;
wire   [7:0] tmp_13_fu_483_p1;
wire   [7:0] tmp_22_fu_519_p1;
wire   [7:0] tmp_14_fu_487_p1;
wire   [10:0] tmp_23_fu_617_p4;
wire   [12:0] row_cast_cast_i_i_fu_597_p1;
wire   [0:0] tmp_43_i_i_fu_671_p2;
wire   [10:0] tmp_25_fu_708_p4;
wire   [12:0] col_assign_cast_cast_i_i_fu_686_p1;
wire   [0:0] icmp1_fu_718_p2;
wire   [0:0] tmp_42_i_i_fu_724_p2;
wire  signed [7:0] grp_fu_808_p0;
wire   [7:0] grp_fu_808_p1;
wire  signed [7:0] grp_fu_813_p0;
wire   [7:0] grp_fu_813_p1;
wire  signed [7:0] grp_fu_821_p0;
wire   [7:0] grp_fu_821_p1;
wire  signed [7:0] grp_fu_826_p0;
wire   [7:0] grp_fu_826_p1;
wire  signed [7:0] grp_fu_835_p0;
wire   [7:0] grp_fu_835_p1;
wire  signed [7:0] grp_fu_840_p0;
wire   [7:0] grp_fu_840_p1;
wire  signed [7:0] grp_fu_848_p0;
wire   [7:0] grp_fu_848_p1;
wire  signed [7:0] grp_fu_853_p0;
wire   [7:0] grp_fu_853_p1;
wire  signed [7:0] grp_fu_861_p0;
wire   [7:0] grp_fu_861_p1;
wire  signed [7:0] grp_fu_866_p0;
wire   [7:0] grp_fu_866_p1;
wire  signed [7:0] grp_fu_875_p0;
wire   [7:0] grp_fu_875_p1;
wire  signed [7:0] grp_fu_880_p0;
wire   [7:0] grp_fu_880_p1;
wire  signed [7:0] grp_fu_888_p0;
wire   [7:0] grp_fu_888_p1;
wire  signed [7:0] grp_fu_893_p0;
wire   [7:0] grp_fu_893_p1;
wire  signed [7:0] grp_fu_901_p0;
wire   [7:0] grp_fu_901_p1;
wire  signed [7:0] grp_fu_906_p0;
wire   [7:0] grp_fu_906_p1;
wire  signed [7:0] grp_fu_915_p0;
wire   [7:0] grp_fu_915_p1;
wire   [15:0] tmp2_fu_932_p2;
wire   [15:0] tmp3_fu_936_p2;
wire   [15:0] tmp6_fu_950_p2;
wire   [15:0] tmp9_fu_959_p2;
wire   [15:0] tmp10_fu_963_p2;
wire   [15:0] tmp13_fu_977_p2;
wire   [15:0] tmp8_fu_986_p2;
wire   [15:0] tmp15_fu_995_p2;
wire   [0:0] tmp_17_i_i_i_fu_1004_p2;
wire   [15:0] tmp_18_i_i_i_fu_1009_p2;
wire   [0:0] tmp_20_i_i_i_fu_1021_p2;
wire   [15:0] tmp_21_i_i_i_fu_1026_p2;
wire   [15:0] edge_weight_fu_1038_p2;
wire   [7:0] tmp_26_fu_1048_p1;
wire   [31:0] tmp_25_i_i_i_fu_1064_p1;
wire   [0:0] tmp_s_fu_1085_p2;
wire   [7:0] p_edge_val_i_i_i_fu_1078_p3;
wire   [7:0] edge_val_3_fu_1102_p3;
reg    grp_fu_808_ce;
reg    grp_fu_813_ce;
reg    grp_fu_821_ce;
reg    grp_fu_826_ce;
reg    grp_fu_835_ce;
reg    grp_fu_840_ce;
reg    grp_fu_848_ce;
reg    grp_fu_853_ce;
reg    grp_fu_861_ce;
reg    grp_fu_866_ce;
reg    grp_fu_875_ce;
reg    grp_fu_880_ce;
reg    grp_fu_888_ce;
reg    grp_fu_893_ce;
reg    grp_fu_901_ce;
reg    grp_fu_906_ce;
reg    grp_fu_915_ce;
reg   [3:0] ap_NS_fsm;
wire   [15:0] grp_fu_915_p10;


image_filter_sobel_filter_core_buff_A_val_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buff_A_val_0_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buff_A_val_0_address0 ),
    .ce0( buff_A_val_0_ce0 ),
    .q0( buff_A_val_0_q0 ),
    .address1( buff_A_val_0_address1 ),
    .ce1( buff_A_val_0_ce1 ),
    .we1( buff_A_val_0_we1 ),
    .d1( buff_A_val_0_d1 )
);

image_filter_sobel_filter_core_buff_A_val_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buff_A_val_1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buff_A_val_1_address0 ),
    .ce0( buff_A_val_1_ce0 ),
    .q0( buff_A_val_1_q0 ),
    .address1( buff_A_val_1_address1 ),
    .ce1( buff_A_val_1_ce1 ),
    .we1( buff_A_val_1_we1 ),
    .d1( buff_A_val_1_d1 )
);

image_filter_sobel_filter_core_buff_A_val_2 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buff_A_val_2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buff_A_val_2_address0 ),
    .ce0( buff_A_val_2_ce0 ),
    .we0( buff_A_val_2_we0 ),
    .d0( buff_A_val_2_d0 ),
    .address1( buff_A_val_2_address1 ),
    .ce1( buff_A_val_2_ce1 ),
    .q1( buff_A_val_2_q1 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U58(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_808_p0 ),
    .din1( grp_fu_808_p1 ),
    .ce( grp_fu_808_ce ),
    .dout( grp_fu_808_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U59(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_813_p0 ),
    .din1( grp_fu_813_p1 ),
    .ce( grp_fu_813_ce ),
    .dout( grp_fu_813_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U60(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_821_p0 ),
    .din1( grp_fu_821_p1 ),
    .ce( grp_fu_821_ce ),
    .dout( grp_fu_821_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U61(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_826_p0 ),
    .din1( grp_fu_826_p1 ),
    .ce( grp_fu_826_ce ),
    .dout( grp_fu_826_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U62(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_835_p0 ),
    .din1( grp_fu_835_p1 ),
    .ce( grp_fu_835_ce ),
    .dout( grp_fu_835_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U63(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_840_p0 ),
    .din1( grp_fu_840_p1 ),
    .ce( grp_fu_840_ce ),
    .dout( grp_fu_840_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U64(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_848_p0 ),
    .din1( grp_fu_848_p1 ),
    .ce( grp_fu_848_ce ),
    .dout( grp_fu_848_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U65(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_853_p0 ),
    .din1( grp_fu_853_p1 ),
    .ce( grp_fu_853_ce ),
    .dout( grp_fu_853_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U66(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_861_p0 ),
    .din1( grp_fu_861_p1 ),
    .ce( grp_fu_861_ce ),
    .dout( grp_fu_861_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U67(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_866_p0 ),
    .din1( grp_fu_866_p1 ),
    .ce( grp_fu_866_ce ),
    .dout( grp_fu_866_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U68(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_875_p0 ),
    .din1( grp_fu_875_p1 ),
    .ce( grp_fu_875_ce ),
    .dout( grp_fu_875_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U69(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_880_p0 ),
    .din1( grp_fu_880_p1 ),
    .ce( grp_fu_880_ce ),
    .dout( grp_fu_880_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U70(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_888_p0 ),
    .din1( grp_fu_888_p1 ),
    .ce( grp_fu_888_ce ),
    .dout( grp_fu_888_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U71(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_893_p0 ),
    .din1( grp_fu_893_p1 ),
    .ce( grp_fu_893_ce ),
    .dout( grp_fu_893_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U72(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_901_p0 ),
    .din1( grp_fu_901_p1 ),
    .ce( grp_fu_901_ce ),
    .dout( grp_fu_901_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U73(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_906_p0 ),
    .din1( grp_fu_906_p1 ),
    .ce( grp_fu_906_ce ),
    .dout( grp_fu_906_p2 )
);

image_filter_mul_8s_8ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
image_filter_mul_8s_8ns_16_3_U74(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_915_p0 ),
    .din1( grp_fu_915_p1 ),
    .ce( grp_fu_915_ce ),
    .dout( grp_fu_915_p2 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_lv1_0 == exitcond1_fu_601_p2))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & ~(ap_const_lv1_0 == exitcond_fu_644_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == exitcond1_fu_601_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == exitcond1_fu_601_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it10
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it10 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
            ap_reg_ppiten_pp0_it10 <= ap_reg_ppiten_pp0_it9;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it11
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it11 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
            ap_reg_ppiten_pp0_it11 <= ap_reg_ppiten_pp0_it10;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it12
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it12 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
            ap_reg_ppiten_pp0_it12 <= ap_reg_ppiten_pp0_it11;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it13
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it13 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
            ap_reg_ppiten_pp0_it13 <= ap_reg_ppiten_pp0_it12;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it14
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it14 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
            ap_reg_ppiten_pp0_it14 <= ap_reg_ppiten_pp0_it13;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == exitcond1_fu_601_p2))) begin
            ap_reg_ppiten_pp0_it14 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
            if (~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) begin
                ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) begin
                ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
            end
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it8
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it9
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it9 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
            ap_reg_ppiten_pp0_it9 <= ap_reg_ppiten_pp0_it8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (exitcond_reg_1324 == ap_const_lv1_0))) begin
        col_assign_reg_395 <= col_reg_1328;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == exitcond1_fu_601_p2))) begin
        col_assign_reg_395 <= ap_const_lv12_0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_3)) begin
        row_i_i_reg_384 <= row_reg_1299;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        row_i_i_reg_384 <= ap_const_lv12_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        ap_reg_ppstg_buff_A_val_1_addr_reg_1345_pp0_it1 <= buff_A_val_1_addr_reg_1345;
        ap_reg_ppstg_col_assign_reg_395_pp0_it1 <= col_assign_reg_395;
        ap_reg_ppstg_exitcond_reg_1324_pp0_it1 <= exitcond_reg_1324;
        ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it1 <= or_cond3_i_i_reg_1360;
        ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it1 <= or_cond_i_i_reg_1356;
        ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it1 <= tmp_37_i_i_reg_1333;
        ap_reg_ppstg_tmp_38_i_i_reg_1340_pp0_it1[11 : 0] <= tmp_38_i_i_reg_1340[11 : 0];
        exitcond_reg_1324 <= exitcond_fu_644_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14)))) begin
        ap_reg_ppstg_col_assign_reg_395_pp0_it2 <= ap_reg_ppstg_col_assign_reg_395_pp0_it1;
        ap_reg_ppstg_exitcond_reg_1324_pp0_it2 <= ap_reg_ppstg_exitcond_reg_1324_pp0_it1;
        ap_reg_ppstg_exitcond_reg_1324_pp0_it3 <= ap_reg_ppstg_exitcond_reg_1324_pp0_it2;
        ap_reg_ppstg_exitcond_reg_1324_pp0_it4 <= ap_reg_ppstg_exitcond_reg_1324_pp0_it3;
        ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it10 <= ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it9;
        ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it11 <= ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it10;
        ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it12 <= ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it11;
        ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it13 <= ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it12;
        ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it2 <= ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it1;
        ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it3 <= ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it2;
        ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it4 <= ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it3;
        ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it5 <= ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it4;
        ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it6 <= ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it5;
        ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it7 <= ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it6;
        ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it8 <= ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it7;
        ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it9 <= ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it8;
        ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it10 <= ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it9;
        ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it11 <= ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it10;
        ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it12 <= ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it11;
        ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it13 <= ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it12;
        ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it5 <= or_cond4_i_i_reg_1426;
        ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it6 <= ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it5;
        ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it7 <= ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it6;
        ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it8 <= ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it7;
        ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it9 <= ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it8;
        ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it2 <= ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it1;
        ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it2 <= ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it1;
        ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it3 <= ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it2;
        buff_C_val_2_1_reg_1395 <= buff_C_val_2_0_i_i_fu_152;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == exitcond_fu_644_p2) & ~(ap_const_lv1_0 == tmp_37_i_i_fu_655_p2))) begin
        buff_A_val_1_addr_reg_1345 <= tmp_38_i_i_fu_660_p1;
        tmp_38_i_i_reg_1340[11 : 0] <= tmp_38_i_i_fu_660_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (exitcond_reg_1324 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_37_i_i_reg_1333))) begin
        buff_A_val_1_load_reg_1364 <= buff_A_val_1_q0;
        temp_reg_1369 <= buff_A_val_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_ppstg_exitcond_reg_1324_pp0_it2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        buff_C_val_0_0_1_fu_136 <= src_data_stream_0_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1324_pp0_it3))) begin
        buff_C_val_0_0_i_i_fu_128 <= buff_C_val_0_0_fu_764_p3;
        buff_C_val_1_0_i_i_fu_140 <= buff_C_val_1_0_fu_758_p3;
        buff_C_val_2_0_i_i_fu_152 <= buff_C_val_2_0_fu_751_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1324_pp0_it3))) begin
        buff_C_val_0_0_i_i_load_1_reg_1401 <= buff_C_val_0_0_i_i_fu_128;
        buff_C_val_0_0_i_i_load_reg_1431 <= buff_C_val_0_0_i_i_fu_128;
        buff_C_val_0_0_reg_1421 <= buff_C_val_0_0_fu_764_p3;
        buff_C_val_1_0_i_i_load_1_reg_1406 <= buff_C_val_1_0_i_i_fu_140;
        buff_C_val_1_0_i_i_load_reg_1436 <= buff_C_val_1_0_i_i_fu_140;
        buff_C_val_1_0_reg_1416 <= buff_C_val_1_0_fu_758_p3;
        buff_C_val_2_0_reg_1411 <= buff_C_val_2_0_fu_751_p3;
        or_cond4_i_i_reg_1426 <= or_cond4_i_i_fu_771_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1324_pp0_it4))) begin
        buff_C_val_0_1_i_i_fu_132 <= buff_C_val_0_0_i_i_load_reg_1431;
        buff_C_val_1_1_i_i_fu_144 <= buff_C_val_1_0_i_i_load_reg_1436;
        buff_C_val_2_1_i_i_fu_148 <= buff_C_val_2_1_reg_1395;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1324_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it1))) begin
        buff_C_val_1_0_1_fu_124 <= temp_reg_1369;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_ppstg_exitcond_reg_1324_pp0_it2 == ap_const_lv1_0) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it2))) begin
        buff_C_val_1_0_1_load_reg_1375 <= buff_C_val_1_0_1_fu_124;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        c_high_thresh_read_reg_1165 <= c_high_thresh_dout;
        c_low_thresh_read_reg_1170 <= c_low_thresh_dout;
        cols_cast_i_i_cast_reg_1185[10 : 0] <= cols_cast_i_i_cast_fu_429_p1[10 : 0];
        rows_cast_i_i_cast_reg_1175[10 : 0] <= rows_cast_i_i_cast_fu_415_p1[10 : 0];
        tmp_28_i_i_i_reg_1290 <= tmp_28_i_i_i_fu_591_p2;
        tmp_29_i_i_cast_reg_1180 <= tmp_29_i_i_cast_fu_425_p1;
        tmp_30_i_i_cast_reg_1190 <= tmp_30_i_i_cast_fu_439_p1;
        tmp_36_0_1_i_i_i_reg_1215 <= tmp_36_0_1_i_i_i_fu_531_p1;
        tmp_36_0_2_i_i_i_reg_1225 <= tmp_36_0_2_i_i_i_fu_539_p1;
        tmp_36_0_i_i_i_reg_1205 <= tmp_36_0_i_i_i_fu_523_p1;
        tmp_36_1_1_i_i_i_reg_1245 <= tmp_36_1_1_i_i_i_fu_555_p1;
        tmp_36_1_2_i_i_i_reg_1255 <= tmp_36_1_2_i_i_i_fu_563_p1;
        tmp_36_1_i_i_i_reg_1235 <= tmp_36_1_i_i_i_fu_547_p1;
        tmp_36_2_1_i_i_i_reg_1275 <= tmp_36_2_1_i_i_i_fu_579_p1;
        tmp_36_2_2_i_i_i_reg_1285 <= tmp_36_2_2_i_i_i_fu_587_p1;
        tmp_36_2_i_i_i_reg_1265 <= tmp_36_2_i_i_i_fu_571_p1;
        tmp_38_0_1_i_i_i_reg_1220 <= tmp_38_0_1_i_i_i_fu_535_p1;
        tmp_38_0_2_i_i_i_reg_1230 <= tmp_38_0_2_i_i_i_fu_543_p1;
        tmp_38_0_i_i_i_reg_1210 <= tmp_38_0_i_i_i_fu_527_p1;
        tmp_38_1_1_i_i_i_reg_1250 <= tmp_38_1_1_i_i_i_fu_559_p1;
        tmp_38_1_2_i_i_i_reg_1260 <= tmp_38_1_2_i_i_i_fu_567_p1;
        tmp_38_1_i_i_i_reg_1240 <= tmp_38_1_i_i_i_fu_551_p1;
        tmp_38_2_1_i_i_i_reg_1280 <= tmp_38_2_1_i_i_i_fu_583_p1;
        tmp_38_2_i_i_i_reg_1270 <= tmp_38_2_i_i_i_fu_575_p1;
        tmp_3_reg_1195 <= tmp_3_fu_443_p2;
        tmp_6_reg_1200 <= tmp_6_fu_449_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        col_reg_1328 <= col_fu_649_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it11))) begin
        edge_val1_i_i_i_reg_1644 <= edge_val1_i_i_i_fu_1058_p3;
        tmp_26_i_i_i_reg_1649 <= tmp_26_i_i_i_fu_1068_p2;
        tmp_27_i_i_i_reg_1655 <= tmp_27_i_i_i_fu_1073_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it12) & ~(ap_const_lv1_0 == tmp_28_i_i_i_reg_1290))) begin
        edge_val_1_reg_1665 <= edge_val_1_fu_1096_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it12))) begin
        edge_val_2_i_i_i_reg_1660 <= edge_val_2_i_i_i_fu_1089_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it10))) begin
        edge_val_reg_1639 <= edge_val_fu_1052_p2;
        tmp_23_i_i_i_reg_1634 <= tmp_23_i_i_i_fu_1042_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_lv1_0 == exitcond1_fu_601_p2))) begin
        icmp_reg_1309 <= icmp_fu_627_p2;
        tmp_32_i_i_reg_1304 <= tmp_32_i_i_fu_612_p2;
        tmp_34_i_i_reg_1314 <= tmp_34_i_i_fu_633_p2;
        tmp_35_i_i_reg_1319 <= tmp_35_i_i_fu_639_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == exitcond_fu_644_p2))) begin
        or_cond3_i_i_reg_1360 <= or_cond3_i_i_fu_677_p2;
        or_cond_i_i_reg_1356 <= or_cond_i_i_fu_666_p2;
        tmp_37_i_i_reg_1333 <= tmp_37_i_i_fu_655_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        row_reg_1299 <= row_fu_606_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it7))) begin
        tmp11_reg_1595 <= tmp11_fu_967_p2;
        tmp12_reg_1600 <= tmp12_fu_973_p2;
        tmp14_reg_1605 <= tmp14_fu_981_p2;
        tmp4_reg_1580 <= tmp4_fu_940_p2;
        tmp5_reg_1585 <= tmp5_fu_946_p2;
        tmp7_reg_1590 <= tmp7_fu_954_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_ppstg_exitcond_reg_1324_pp0_it2 == ap_const_lv1_0) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        tmp1_reg_1390 <= tmp1_fu_734_p2;
        tmp_reg_1385 <= tmp_fu_729_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it9))) begin
        tmp_19_i_i_i_reg_1624 <= tmp_19_i_i_i_fu_1014_p3;
        tmp_22_i_i_i_reg_1629 <= tmp_22_i_i_i_fu_1031_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it6))) begin
        tmp_37_0_1_i_i_i_reg_1504 <= grp_fu_821_p2;
        tmp_37_0_2_i_i_i_reg_1514 <= grp_fu_835_p2;
        tmp_37_0_i_i_i_reg_1494 <= grp_fu_808_p2;
        tmp_37_1_1_i_i_i_reg_1534 <= grp_fu_861_p2;
        tmp_37_1_2_i_i_i_reg_1544 <= grp_fu_875_p2;
        tmp_37_1_i_i_i_reg_1524 <= grp_fu_848_p2;
        tmp_37_2_1_i_i_i_reg_1564 <= grp_fu_901_p2;
        tmp_37_2_2_i_i_i_reg_1574 <= grp_fu_915_p2;
        tmp_37_2_i_i_i_reg_1554 <= grp_fu_888_p2;
        tmp_39_0_1_i_i_i_reg_1509 <= grp_fu_826_p2;
        tmp_39_0_2_i_i_i_reg_1519 <= grp_fu_840_p2;
        tmp_39_0_i_i_i_reg_1499 <= grp_fu_813_p2;
        tmp_39_1_1_i_i_i_reg_1539 <= grp_fu_866_p2;
        tmp_39_1_2_i_i_i_reg_1549 <= grp_fu_880_p2;
        tmp_39_1_i_i_i_reg_1529 <= grp_fu_853_p2;
        tmp_39_2_1_i_i_i_reg_1569 <= grp_fu_906_p2;
        tmp_39_2_i_i_i_reg_1559 <= grp_fu_893_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it8))) begin
        x_weight_2_2_2_i_i_i_reg_1610 <= x_weight_2_2_2_i_i_i_fu_990_p2;
        y_weight_2_2_2_i_i_i_reg_1617 <= y_weight_2_2_2_i_i_i_fu_999_p2;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_XR0C0_read = ap_const_logic_1;
    end else begin
        C_XR0C0_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_XR0C1_read = ap_const_logic_1;
    end else begin
        C_XR0C1_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_XR0C2_read = ap_const_logic_1;
    end else begin
        C_XR0C2_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_XR1C0_read = ap_const_logic_1;
    end else begin
        C_XR1C0_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_XR1C1_read = ap_const_logic_1;
    end else begin
        C_XR1C1_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_XR1C2_read = ap_const_logic_1;
    end else begin
        C_XR1C2_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_XR2C0_read = ap_const_logic_1;
    end else begin
        C_XR2C0_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_XR2C1_read = ap_const_logic_1;
    end else begin
        C_XR2C1_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_XR2C2_read = ap_const_logic_1;
    end else begin
        C_XR2C2_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_YR0C0_read = ap_const_logic_1;
    end else begin
        C_YR0C0_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_YR0C1_read = ap_const_logic_1;
    end else begin
        C_YR0C1_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_YR0C2_read = ap_const_logic_1;
    end else begin
        C_YR0C2_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_YR1C0_read = ap_const_logic_1;
    end else begin
        C_YR1C0_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_YR1C1_read = ap_const_logic_1;
    end else begin
        C_YR1C1_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_YR1C2_read = ap_const_logic_1;
    end else begin
        C_YR1C2_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_YR2C0_read = ap_const_logic_1;
    end else begin
        C_YR2C0_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        C_YR2C1_read = ap_const_logic_1;
    end else begin
        C_YR2C1_read = ap_const_logic_0;
    end
end

always @ (ap_done_reg or exitcond1_fu_601_p2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_lv1_0 == exitcond1_fu_601_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (exitcond1_fu_601_p2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(ap_const_lv1_0 == exitcond1_fu_601_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_142) begin
    if (ap_sig_bdd_142) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_609) begin
    if (ap_sig_bdd_609) begin
        ap_sig_cseq_ST_st18_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_23) begin
    if (ap_sig_bdd_23) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_314) begin
    if (ap_sig_bdd_314) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        buff_A_val_0_ce0 = ap_const_logic_1;
    end else begin
        buff_A_val_0_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        buff_A_val_0_ce1 = ap_const_logic_1;
    end else begin
        buff_A_val_0_ce1 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppstg_exitcond_reg_1324_pp0_it2 or ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_reg_ppstg_exitcond_reg_1324_pp0_it2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        buff_A_val_0_we1 = ap_const_logic_1;
    end else begin
        buff_A_val_0_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        buff_A_val_1_ce0 = ap_const_logic_1;
    end else begin
        buff_A_val_1_ce0 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        buff_A_val_1_ce1 = ap_const_logic_1;
    end else begin
        buff_A_val_1_ce1 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14 or ap_reg_ppstg_exitcond_reg_1324_pp0_it1 or ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it1) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1324_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it1))) begin
        buff_A_val_1_we1 = ap_const_logic_1;
    end else begin
        buff_A_val_1_we1 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        buff_A_val_2_ce0 = ap_const_logic_1;
    end else begin
        buff_A_val_2_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        buff_A_val_2_ce1 = ap_const_logic_1;
    end else begin
        buff_A_val_2_ce1 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14 or ap_reg_ppstg_exitcond_reg_1324_pp0_it1 or ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it1) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1324_pp0_it1) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it1))) begin
        buff_A_val_2_we0 = ap_const_logic_1;
    end else begin
        buff_A_val_2_we0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        c_high_thresh_read = ap_const_logic_1;
    end else begin
        c_high_thresh_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        c_invert_read = ap_const_logic_1;
    end else begin
        c_invert_read = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        c_low_thresh_read = ap_const_logic_1;
    end else begin
        c_low_thresh_read = ap_const_logic_0;
    end
end

always @ (col_assign_reg_395 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppiten_pp0_it1 or exitcond_reg_1324 or col_reg_1328) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_1324 == ap_const_lv1_0))) begin
        col_assign_phi_fu_399_p4 = col_reg_1328;
    end else begin
        col_assign_phi_fu_399_p4 = col_assign_reg_395;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        cols_read = ap_const_logic_1;
    end else begin
        cols_read = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it13 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it13) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        dst_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        dst_data_stream_0_V_write = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it13 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it13) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        dst_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        dst_data_stream_1_V_write = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_808_ce = ap_const_logic_1;
    end else begin
        grp_fu_808_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_813_ce = ap_const_logic_1;
    end else begin
        grp_fu_813_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_821_ce = ap_const_logic_1;
    end else begin
        grp_fu_821_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_826_ce = ap_const_logic_1;
    end else begin
        grp_fu_826_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_835_ce = ap_const_logic_1;
    end else begin
        grp_fu_835_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_840_ce = ap_const_logic_1;
    end else begin
        grp_fu_840_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_848_ce = ap_const_logic_1;
    end else begin
        grp_fu_848_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_853_ce = ap_const_logic_1;
    end else begin
        grp_fu_853_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_861_ce = ap_const_logic_1;
    end else begin
        grp_fu_861_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_866_ce = ap_const_logic_1;
    end else begin
        grp_fu_866_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_875_ce = ap_const_logic_1;
    end else begin
        grp_fu_875_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_880_ce = ap_const_logic_1;
    end else begin
        grp_fu_880_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_888_ce = ap_const_logic_1;
    end else begin
        grp_fu_888_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_893_ce = ap_const_logic_1;
    end else begin
        grp_fu_893_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_901_ce = ap_const_logic_1;
    end else begin
        grp_fu_901_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_906_ce = ap_const_logic_1;
    end else begin
        grp_fu_906_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        grp_fu_915_ce = ap_const_logic_1;
    end else begin
        grp_fu_915_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_254) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_254)) begin
        rows_read = ap_const_logic_1;
    end else begin
        rows_read = ap_const_logic_0;
    end
end

always @ (ap_reg_ppstg_exitcond_reg_1324_pp0_it2 or ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_reg_ppstg_exitcond_reg_1324_pp0_it2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        src_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        src_data_stream_0_V_read = ap_const_logic_0;
    end
end

always @ (ap_reg_ppstg_exitcond_reg_1324_pp0_it2 or ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it2 or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14) begin
    if (((ap_reg_ppstg_exitcond_reg_1324_pp0_it2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))))) begin
        src_data_stream_1_V_read = ap_const_logic_1;
    end else begin
        src_data_stream_1_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_164 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it5 or ap_reg_ppiten_pp0_it13 or ap_sig_bdd_197 or ap_reg_ppiten_pp0_it14 or ap_sig_bdd_254 or exitcond1_fu_601_p2) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_254) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(ap_const_lv1_0 == exitcond1_fu_601_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it14) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it13)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it14) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it13)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_164 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) | (ap_sig_bdd_197 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it14))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
                ap_NS_fsm = ap_ST_st18_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_st18_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_CS_fsm) begin
    ap_sig_bdd_142 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (src_data_stream_0_V_empty_n or src_data_stream_1_V_empty_n or ap_reg_ppstg_exitcond_reg_1324_pp0_it2 or ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it2) begin
    ap_sig_bdd_164 = (((src_data_stream_0_V_empty_n == ap_const_logic_0) & (ap_reg_ppstg_exitcond_reg_1324_pp0_it2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it2)) | ((ap_reg_ppstg_exitcond_reg_1324_pp0_it2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1356_pp0_it2) & (src_data_stream_1_V_empty_n == ap_const_logic_0)));
end


always @ (dst_data_stream_0_V_full_n or dst_data_stream_1_V_full_n or ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it13) begin
    ap_sig_bdd_197 = (((dst_data_stream_0_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it13)) | (~(ap_const_lv1_0 == ap_reg_ppstg_or_cond3_i_i_reg_1360_pp0_it13) & (dst_data_stream_1_V_full_n == ap_const_logic_0)));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_23 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_start or ap_done_reg or rows_empty_n or cols_empty_n or C_XR0C0_empty_n or C_XR0C1_empty_n or C_XR0C2_empty_n or C_XR1C0_empty_n or C_XR1C1_empty_n or C_XR1C2_empty_n or C_XR2C0_empty_n or C_XR2C1_empty_n or C_XR2C2_empty_n or C_YR0C0_empty_n or C_YR0C1_empty_n or C_YR0C2_empty_n or C_YR1C0_empty_n or C_YR1C1_empty_n or C_YR1C2_empty_n or C_YR2C0_empty_n or C_YR2C1_empty_n or c_high_thresh_empty_n or c_low_thresh_empty_n or c_invert_empty_n) begin
    ap_sig_bdd_254 = ((rows_empty_n == ap_const_logic_0) | (cols_empty_n == ap_const_logic_0) | (C_XR0C0_empty_n == ap_const_logic_0) | (C_XR0C1_empty_n == ap_const_logic_0) | (C_XR0C2_empty_n == ap_const_logic_0) | (C_XR1C0_empty_n == ap_const_logic_0) | (C_XR1C1_empty_n == ap_const_logic_0) | (C_XR1C2_empty_n == ap_const_logic_0) | (C_XR2C0_empty_n == ap_const_logic_0) | (C_XR2C1_empty_n == ap_const_logic_0) | (C_XR2C2_empty_n == ap_const_logic_0) | (C_YR0C0_empty_n == ap_const_logic_0) | (C_YR0C1_empty_n == ap_const_logic_0) | (C_YR0C2_empty_n == ap_const_logic_0) | (C_YR1C0_empty_n == ap_const_logic_0) | (C_YR1C1_empty_n == ap_const_logic_0) | (C_YR1C2_empty_n == ap_const_logic_0) | (C_YR2C0_empty_n == ap_const_logic_0) | (C_YR2C1_empty_n == ap_const_logic_0) | (c_high_thresh_empty_n == ap_const_logic_0) | (c_low_thresh_empty_n == ap_const_logic_0) | (c_invert_empty_n == ap_const_logic_0) | (ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_314 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_609 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

assign buff_A_val_0_address0 = tmp_38_i_i_fu_660_p1;

assign buff_A_val_0_address1 = tmp_39_i_i_fu_690_p1;

assign buff_A_val_0_d1 = src_data_stream_0_V_dout;

assign buff_A_val_1_address0 = tmp_38_i_i_fu_660_p1;

assign buff_A_val_1_address1 = ap_reg_ppstg_buff_A_val_1_addr_reg_1345_pp0_it1;

assign buff_A_val_1_d1 = temp_reg_1369;

assign buff_A_val_2_address0 = ap_reg_ppstg_tmp_38_i_i_reg_1340_pp0_it1;

assign buff_A_val_2_address1 = tmp_40_i_i_fu_703_p1;

assign buff_A_val_2_d0 = buff_A_val_1_load_reg_1364;

assign buff_C_val_0_0_fu_764_p3 = ((ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it3[0:0] === 1'b1) ? buff_C_val_0_0_1_fu_136 : buff_C_val_0_0_i_i_fu_128);

assign buff_C_val_1_0_fu_758_p3 = ((ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it3[0:0] === 1'b1) ? buff_C_val_1_0_1_load_reg_1375 : buff_C_val_1_0_i_i_fu_140);

assign buff_C_val_2_0_fu_751_p3 = ((ap_reg_ppstg_tmp_37_i_i_reg_1333_pp0_it3[0:0] === 1'b1) ? buff_A_val_2_q1 : buff_C_val_2_0_i_i_fu_152);

assign col_assign_cast_cast_i_i_fu_686_p1 = ap_reg_ppstg_col_assign_reg_395_pp0_it2;

assign col_fu_649_p2 = (col_assign_phi_fu_399_p4 + ap_const_lv12_1);

assign cols_cast_i_i_cast_fu_429_p1 = tmp_2_fu_411_p1;

assign dst_data_stream_0_V_din = ((ap_reg_ppstg_or_cond4_i_i_reg_1426_pp0_it13[0:0] === 1'b1) ? ap_const_lv8_0 : edge_val_3_fu_1102_p3);

assign dst_data_stream_1_V_din = ap_const_lv8_80;

assign edge_val1_i_i_i_fu_1058_p3 = ((tmp_23_i_i_i_reg_1634[0:0] === 1'b1) ? edge_val_reg_1639 : ap_const_lv8_0);

assign edge_val_1_fu_1096_p2 = (edge_val_2_i_i_i_fu_1089_p3 ^ ap_const_lv8_FF);

assign edge_val_2_i_i_i_fu_1089_p3 = ((tmp_s_fu_1085_p2[0:0] === 1'b1) ? p_edge_val_i_i_i_fu_1078_p3 : edge_val1_i_i_i_reg_1644);

assign edge_val_3_fu_1102_p3 = ((tmp_28_i_i_i_reg_1290[0:0] === 1'b1) ? edge_val_1_reg_1665 : edge_val_2_i_i_i_reg_1660);

assign edge_val_fu_1052_p2 = (tmp_26_fu_1048_p1 ^ ap_const_lv8_FF);

assign edge_weight_fu_1038_p2 = (tmp_22_i_i_i_reg_1629 + tmp_19_i_i_i_reg_1624);

assign exitcond1_fu_601_p2 = (row_i_i_reg_384 == tmp_6_reg_1200? 1'b1: 1'b0);

assign exitcond_fu_644_p2 = (col_assign_phi_fu_399_p4 == tmp_3_reg_1195? 1'b1: 1'b0);

assign grp_fu_808_p0 = tmp_36_0_i_i_i_reg_1205;

assign grp_fu_808_p1 = tmp_35_0_i_i_i_fu_805_p1;

assign grp_fu_813_p0 = tmp_38_0_i_i_i_reg_1210;

assign grp_fu_813_p1 = tmp_35_0_i_i_i_fu_805_p1;

assign grp_fu_821_p0 = tmp_36_0_1_i_i_i_reg_1215;

assign grp_fu_821_p1 = tmp_35_0_1_i_i_i_fu_818_p1;

assign grp_fu_826_p0 = tmp_38_0_1_i_i_i_reg_1220;

assign grp_fu_826_p1 = tmp_35_0_1_i_i_i_fu_818_p1;

assign grp_fu_835_p0 = tmp_36_0_2_i_i_i_reg_1225;

assign grp_fu_835_p1 = tmp_35_0_2_i_i_i_fu_831_p1;

assign grp_fu_840_p0 = tmp_38_0_2_i_i_i_reg_1230;

assign grp_fu_840_p1 = tmp_35_0_2_i_i_i_fu_831_p1;

assign grp_fu_848_p0 = tmp_36_1_i_i_i_reg_1235;

assign grp_fu_848_p1 = tmp_35_1_i_i_i_fu_845_p1;

assign grp_fu_853_p0 = tmp_38_1_i_i_i_reg_1240;

assign grp_fu_853_p1 = tmp_35_1_i_i_i_fu_845_p1;

assign grp_fu_861_p0 = tmp_36_1_1_i_i_i_reg_1245;

assign grp_fu_861_p1 = tmp_35_1_1_i_i_i_fu_858_p1;

assign grp_fu_866_p0 = tmp_38_1_1_i_i_i_reg_1250;

assign grp_fu_866_p1 = tmp_35_1_1_i_i_i_fu_858_p1;

assign grp_fu_875_p0 = tmp_36_1_2_i_i_i_reg_1255;

assign grp_fu_875_p1 = tmp_35_1_2_i_i_i_fu_871_p1;

assign grp_fu_880_p0 = tmp_38_1_2_i_i_i_reg_1260;

assign grp_fu_880_p1 = tmp_35_1_2_i_i_i_fu_871_p1;

assign grp_fu_888_p0 = tmp_36_2_i_i_i_reg_1265;

assign grp_fu_888_p1 = tmp_35_2_i_i_i_fu_885_p1;

assign grp_fu_893_p0 = tmp_38_2_i_i_i_reg_1270;

assign grp_fu_893_p1 = tmp_35_2_i_i_i_fu_885_p1;

assign grp_fu_901_p0 = tmp_36_2_1_i_i_i_reg_1275;

assign grp_fu_901_p1 = tmp_35_2_1_i_i_i_fu_898_p1;

assign grp_fu_906_p0 = tmp_38_2_1_i_i_i_reg_1280;

assign grp_fu_906_p1 = tmp_35_2_1_i_i_i_fu_898_p1;

assign grp_fu_915_p0 = tmp_36_2_2_i_i_i_reg_1285;

assign grp_fu_915_p1 = grp_fu_915_p10;

assign grp_fu_915_p10 = buff_C_val_2_1_i_i_fu_148;

assign icmp1_fu_718_p2 = (tmp_25_fu_708_p4 == ap_const_lv11_0? 1'b1: 1'b0);

assign icmp_fu_627_p2 = (tmp_23_fu_617_p4 == ap_const_lv11_0? 1'b1: 1'b0);

assign or_cond3_i_i_fu_677_p2 = (tmp_34_i_i_reg_1314 & tmp_43_i_i_fu_671_p2);

assign or_cond4_i_i_fu_771_p2 = (tmp1_reg_1390 | tmp_reg_1385);

assign or_cond_i_i_fu_666_p2 = (tmp_37_i_i_fu_655_p2 & tmp_32_i_i_reg_1304);

assign p_edge_val_i_i_i_fu_1078_p3 = ((tmp_26_i_i_i_reg_1649[0:0] === 1'b1) ? ap_const_lv8_FF : ap_const_lv8_0);

assign row_cast_cast_i_i_fu_597_p1 = row_i_i_reg_384;

assign row_fu_606_p2 = (row_i_i_reg_384 + ap_const_lv12_1);

assign rows_cast_i_i_cast_fu_415_p1 = tmp_1_fu_407_p1;

assign tmp10_fu_963_p2 = (tmp_39_1_1_i_i_i_reg_1539 + tmp_39_1_2_i_i_i_reg_1549);

assign tmp11_fu_967_p2 = (tmp9_fu_959_p2 + tmp10_fu_963_p2);

assign tmp12_fu_973_p2 = (tmp_39_0_i_i_i_reg_1499 + tmp_39_0_1_i_i_i_reg_1509);

assign tmp13_fu_977_p2 = (tmp_37_2_2_i_i_i_reg_1574 + tmp_39_0_2_i_i_i_reg_1519);

assign tmp14_fu_981_p2 = (tmp_39_1_i_i_i_reg_1529 + tmp13_fu_977_p2);

assign tmp15_fu_995_p2 = (tmp12_reg_1600 + tmp14_reg_1605);

assign tmp1_fu_734_p2 = (tmp_35_i_i_reg_1319 | tmp_42_i_i_fu_724_p2);

assign tmp2_fu_932_p2 = (tmp_37_2_1_i_i_i_reg_1564 + tmp_37_2_i_i_i_reg_1554);

assign tmp3_fu_936_p2 = (tmp_37_1_1_i_i_i_reg_1534 + tmp_37_1_2_i_i_i_reg_1544);

assign tmp4_fu_940_p2 = (tmp2_fu_932_p2 + tmp3_fu_936_p2);

assign tmp5_fu_946_p2 = (tmp_37_0_i_i_i_reg_1494 + tmp_37_0_1_i_i_i_reg_1504);

assign tmp6_fu_950_p2 = (tmp_37_2_2_i_i_i_reg_1574 + tmp_37_0_2_i_i_i_reg_1514);

assign tmp7_fu_954_p2 = (tmp_37_1_i_i_i_reg_1524 + tmp6_fu_950_p2);

assign tmp8_fu_986_p2 = (tmp5_reg_1585 + tmp7_reg_1590);

assign tmp9_fu_959_p2 = (tmp_39_2_1_i_i_i_reg_1569 + tmp_39_2_i_i_i_reg_1559);

assign tmp_10_fu_471_p1 = C_XR1C1_dout[7:0];

assign tmp_11_fu_475_p1 = C_XR1C2_dout[7:0];

assign tmp_12_fu_479_p1 = C_XR2C0_dout[7:0];

assign tmp_13_fu_483_p1 = C_XR2C1_dout[7:0];

assign tmp_14_fu_487_p1 = C_XR2C2_dout[7:0];

assign tmp_15_fu_491_p1 = C_YR0C0_dout[7:0];

assign tmp_16_fu_495_p1 = C_YR0C1_dout[7:0];

assign tmp_17_fu_499_p1 = C_YR0C2_dout[7:0];

assign tmp_17_i_i_i_fu_1004_p2 = ($signed(x_weight_2_2_2_i_i_i_reg_1610) > $signed(16'b0000000000000000)? 1'b1: 1'b0);

assign tmp_18_fu_503_p1 = C_YR1C0_dout[7:0];

assign tmp_18_i_i_i_fu_1009_p2 = (ap_const_lv16_0 - x_weight_2_2_2_i_i_i_reg_1610);

assign tmp_19_fu_507_p1 = C_YR1C1_dout[7:0];

assign tmp_19_i_i_i_fu_1014_p3 = ((tmp_17_i_i_i_fu_1004_p2[0:0] === 1'b1) ? x_weight_2_2_2_i_i_i_reg_1610 : tmp_18_i_i_i_fu_1009_p2);

assign tmp_1_fu_407_p1 = rows_dout[10:0];

assign tmp_20_fu_511_p1 = C_YR1C2_dout[7:0];

assign tmp_20_i_i_i_fu_1021_p2 = ($signed(y_weight_2_2_2_i_i_i_reg_1617) > $signed(16'b0000000000000000)? 1'b1: 1'b0);

assign tmp_21_fu_515_p1 = C_YR2C0_dout[7:0];

assign tmp_21_i_i_i_fu_1026_p2 = (ap_const_lv16_0 - y_weight_2_2_2_i_i_i_reg_1617);

assign tmp_22_fu_519_p1 = C_YR2C1_dout[7:0];

assign tmp_22_i_i_i_fu_1031_p3 = ((tmp_20_i_i_i_fu_1021_p2[0:0] === 1'b1) ? y_weight_2_2_2_i_i_i_reg_1617 : tmp_21_i_i_i_fu_1026_p2);

assign tmp_23_fu_617_p4 = {{row_i_i_reg_384[ap_const_lv32_B : ap_const_lv32_1]}};

assign tmp_23_i_i_i_fu_1042_p2 = ($signed(edge_weight_fu_1038_p2) < $signed(16'b11111111)? 1'b1: 1'b0);

assign tmp_25_fu_708_p4 = {{ap_reg_ppstg_col_assign_reg_395_pp0_it2[ap_const_lv32_B : ap_const_lv32_1]}};

assign tmp_25_i_i_i_fu_1064_p1 = edge_val1_i_i_i_fu_1058_p3;

assign tmp_26_fu_1048_p1 = edge_weight_fu_1038_p2[7:0];

assign tmp_26_i_i_i_fu_1068_p2 = ($signed(tmp_25_i_i_i_fu_1064_p1) > $signed(c_high_thresh_read_reg_1165)? 1'b1: 1'b0);

assign tmp_27_i_i_i_fu_1073_p2 = ($signed(tmp_25_i_i_i_fu_1064_p1) < $signed(c_low_thresh_read_reg_1170)? 1'b1: 1'b0);

assign tmp_28_i_i_i_fu_591_p2 = (c_invert_dout == ap_const_lv32_1? 1'b1: 1'b0);

assign tmp_29_i_i_cast_fu_425_p1 = $signed(tmp_29_i_i_fu_419_p2);

assign tmp_29_i_i_fu_419_p2 = ($signed(ap_const_lv12_FFF) + $signed(rows_cast_i_i_cast_fu_415_p1));

assign tmp_2_fu_411_p1 = cols_dout[10:0];

assign tmp_30_i_i_cast_fu_439_p1 = $signed(tmp_30_i_i_fu_433_p2);

assign tmp_30_i_i_fu_433_p2 = ($signed(ap_const_lv12_FFF) + $signed(cols_cast_i_i_cast_fu_429_p1));

assign tmp_32_i_i_fu_612_p2 = (row_i_i_reg_384 < rows_cast_i_i_cast_reg_1175? 1'b1: 1'b0);

assign tmp_34_i_i_fu_633_p2 = (row_i_i_reg_384 != ap_const_lv12_0? 1'b1: 1'b0);

assign tmp_35_0_1_i_i_i_fu_818_p1 = buff_C_val_0_0_i_i_load_1_reg_1401;

assign tmp_35_0_2_i_i_i_fu_831_p1 = buff_C_val_0_1_i_i_fu_132;

assign tmp_35_0_i_i_i_fu_805_p1 = buff_C_val_0_0_reg_1421;

assign tmp_35_1_1_i_i_i_fu_858_p1 = buff_C_val_1_0_i_i_load_1_reg_1406;

assign tmp_35_1_2_i_i_i_fu_871_p1 = buff_C_val_1_1_i_i_fu_144;

assign tmp_35_1_i_i_i_fu_845_p1 = buff_C_val_1_0_reg_1416;

assign tmp_35_2_1_i_i_i_fu_898_p1 = buff_C_val_2_1_reg_1395;

assign tmp_35_2_i_i_i_fu_885_p1 = buff_C_val_2_0_reg_1411;

assign tmp_35_i_i_fu_639_p2 = ($signed(row_cast_cast_i_i_fu_597_p1) > $signed(tmp_29_i_i_cast_reg_1180)? 1'b1: 1'b0);

assign tmp_36_0_1_i_i_i_fu_531_p1 = $signed(tmp_5_fu_459_p1);

assign tmp_36_0_2_i_i_i_fu_539_p1 = $signed(tmp_7_fu_463_p1);

assign tmp_36_0_i_i_i_fu_523_p1 = $signed(tmp_4_fu_455_p1);

assign tmp_36_1_1_i_i_i_fu_555_p1 = $signed(tmp_10_fu_471_p1);

assign tmp_36_1_2_i_i_i_fu_563_p1 = $signed(tmp_11_fu_475_p1);

assign tmp_36_1_i_i_i_fu_547_p1 = $signed(tmp_8_fu_467_p1);

assign tmp_36_2_1_i_i_i_fu_579_p1 = $signed(tmp_13_fu_483_p1);

assign tmp_36_2_2_i_i_i_fu_587_p1 = $signed(tmp_14_fu_487_p1);

assign tmp_36_2_i_i_i_fu_571_p1 = $signed(tmp_12_fu_479_p1);

assign tmp_37_i_i_fu_655_p2 = (col_assign_phi_fu_399_p4 < cols_cast_i_i_cast_reg_1185? 1'b1: 1'b0);

assign tmp_38_0_1_i_i_i_fu_535_p1 = $signed(tmp_16_fu_495_p1);

assign tmp_38_0_2_i_i_i_fu_543_p1 = $signed(tmp_17_fu_499_p1);

assign tmp_38_0_i_i_i_fu_527_p1 = $signed(tmp_15_fu_491_p1);

assign tmp_38_1_1_i_i_i_fu_559_p1 = $signed(tmp_19_fu_507_p1);

assign tmp_38_1_2_i_i_i_fu_567_p1 = $signed(tmp_20_fu_511_p1);

assign tmp_38_1_i_i_i_fu_551_p1 = $signed(tmp_18_fu_503_p1);

assign tmp_38_2_1_i_i_i_fu_583_p1 = $signed(tmp_22_fu_519_p1);

assign tmp_38_2_i_i_i_fu_575_p1 = $signed(tmp_21_fu_515_p1);

assign tmp_38_i_i_fu_660_p1 = col_assign_phi_fu_399_p4;

assign tmp_39_i_i_fu_690_p1 = ap_reg_ppstg_col_assign_reg_395_pp0_it2;

assign tmp_3_fu_443_p2 = (ap_const_lv12_1 + cols_cast_i_i_cast_fu_429_p1);

assign tmp_40_i_i_fu_703_p1 = ap_reg_ppstg_col_assign_reg_395_pp0_it2;

assign tmp_42_i_i_fu_724_p2 = ($signed(col_assign_cast_cast_i_i_fu_686_p1) > $signed(tmp_30_i_i_cast_reg_1190)? 1'b1: 1'b0);

assign tmp_43_i_i_fu_671_p2 = (col_assign_phi_fu_399_p4 != ap_const_lv12_0? 1'b1: 1'b0);

assign tmp_4_fu_455_p1 = C_XR0C0_dout[7:0];

assign tmp_5_fu_459_p1 = C_XR0C1_dout[7:0];

assign tmp_6_fu_449_p2 = (ap_const_lv12_1 + rows_cast_i_i_cast_fu_415_p1);

assign tmp_7_fu_463_p1 = C_XR0C2_dout[7:0];

assign tmp_8_fu_467_p1 = C_XR1C0_dout[7:0];

assign tmp_fu_729_p2 = (icmp_reg_1309 | icmp1_fu_718_p2);

assign tmp_s_fu_1085_p2 = (tmp_26_i_i_i_reg_1649 | tmp_27_i_i_i_reg_1655);

assign x_weight_2_2_2_i_i_i_fu_990_p2 = (tmp4_reg_1580 + tmp8_fu_986_p2);

assign y_weight_2_2_2_i_i_i_fu_999_p2 = (tmp11_reg_1595 + tmp15_fu_995_p2);
always @ (posedge ap_clk) begin
    rows_cast_i_i_cast_reg_1175[11] <= 1'b0;
    cols_cast_i_i_cast_reg_1185[11] <= 1'b0;
    tmp_38_i_i_reg_1340[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    ap_reg_ppstg_tmp_38_i_i_reg_1340_pp0_it1[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
end



endmodule //image_filter_sobel_filter_core

