
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.2 EDK_P.68b
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[] =
{
	{
		XPAR_FMC_IMAGEON_IIC_DEVICE_ID,
		XPAR_FMC_IMAGEON_IIC_BASEADDR,
		XPAR_FMC_IMAGEON_IIC_TEN_BIT_ADR,
		XPAR_FMC_IMAGEON_IIC_GPO_WIDTH
	},
	{
		XPAR_IIC_MAIN_DEVICE_ID,
		XPAR_IIC_MAIN_BASEADDR,
		XPAR_IIC_MAIN_TEN_BIT_ADR,
		XPAR_IIC_MAIN_GPO_WIDTH
	}
};


