webtalk_init -webtalk_dir D:\\FMC_IMAGEON_CAMERA\\Projects\\fmc_imageon_gs\\ZC702\\fmc_imageon_gs.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期六 二月 11 13:54:50 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211255574_0_0_367" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f0vbbt7uq4ofp6t4v2bjkv6dkg" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "10.000 GB" -context "user_environment"
webtalk_add_data -client project -key date_generated -value "星期六 二月 11 13:54:37 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ht21eeoc239icfj9eli57tdku" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1486713094887" -context "sdk\\\\hardware/1486713094887"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1486713094887"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1486713094887"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4" -context "sdk\\\\hardware/1486713094887"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1486713094887"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1486713094887"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1486713094887"
webtalk_transmit -clientid 1390690360 -regid "211255574_0_0_367" -xml D:\\FMC_IMAGEON_CAMERA\\Projects\\fmc_imageon_gs\\ZC702\\fmc_imageon_gs.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\FMC_IMAGEON_CAMERA\\Projects\\fmc_imageon_gs\\ZC702\\fmc_imageon_gs.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\FMC_IMAGEON_CAMERA\\Projects\\fmc_imageon_gs\\ZC702\\fmc_imageon_gs.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
