# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/fmc_imageon_gs/zc702_fmc_imageon_gs.xdc

# Block Designs: bd/fmc_imageon_gs/fmc_imageon_gs.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs || ORIG_REF_NAME==fmc_imageon_gs}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_processing_system7_0_0/fmc_imageon_gs_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_processing_system7_0_0 || ORIG_REF_NAME==fmc_imageon_gs_processing_system7_0_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_cfa_0_0/fmc_imageon_gs_v_cfa_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_cfa_0_0 || ORIG_REF_NAME==fmc_imageon_gs_v_cfa_0_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_cresample_0_0/fmc_imageon_gs_v_cresample_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_cresample_0_0 || ORIG_REF_NAME==fmc_imageon_gs_v_cresample_0_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_rgb2ycrcb_0_0/fmc_imageon_gs_v_rgb2ycrcb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==fmc_imageon_gs_v_rgb2ycrcb_0_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_tc_0_0/fmc_imageon_gs_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_tc_0_0 || ORIG_REF_NAME==fmc_imageon_gs_v_tc_0_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_fmc_imageon_iic_0_0/fmc_imageon_gs_fmc_imageon_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_fmc_imageon_iic_0_0 || ORIG_REF_NAME==fmc_imageon_gs_fmc_imageon_iic_0_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_processing_system7_0_axi_periph_0/fmc_imageon_gs_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==fmc_imageon_gs_processing_system7_0_axi_periph_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_xbar_1/fmc_imageon_gs_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_xbar_1 || ORIG_REF_NAME==fmc_imageon_gs_xbar_1}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_rst_processing_system7_0_76M_0/fmc_imageon_gs_rst_processing_system7_0_76M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M_0 || ORIG_REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_axi4s_vid_out_0_0/fmc_imageon_gs_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==fmc_imageon_gs_v_axi4s_vid_out_0_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_vid_in_axi4s_0_0/fmc_imageon_gs_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==fmc_imageon_gs_v_vid_in_axi4s_0_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_xlconstant_0_0/fmc_imageon_gs_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_xlconstant_0_0 || ORIG_REF_NAME==fmc_imageon_gs_xlconstant_0_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_xlconstant_1_0/fmc_imageon_gs_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_xlconstant_1_0 || ORIG_REF_NAME==fmc_imageon_gs_xlconstant_1_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_cfa_0_1/fmc_imageon_gs_v_cfa_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_cfa_0_1 || ORIG_REF_NAME==fmc_imageon_gs_v_cfa_0_1}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_cresample_0_1/fmc_imageon_gs_v_cresample_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_cresample_0_1 || ORIG_REF_NAME==fmc_imageon_gs_v_cresample_0_1}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_rgb2ycrcb_0_1/fmc_imageon_gs_v_rgb2ycrcb_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_rgb2ycrcb_0_1 || ORIG_REF_NAME==fmc_imageon_gs_v_rgb2ycrcb_0_1}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_vid_in_axi4s_0_1/fmc_imageon_gs_v_vid_in_axi4s_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_vid_in_axi4s_0_1 || ORIG_REF_NAME==fmc_imageon_gs_v_vid_in_axi4s_0_1}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_fmc_imageon_iic_0_1/fmc_imageon_gs_fmc_imageon_iic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_fmc_imageon_iic_0_1 || ORIG_REF_NAME==fmc_imageon_gs_fmc_imageon_iic_0_1}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_axi4s_vid_out_0_1/fmc_imageon_gs_v_axi4s_vid_out_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_axi4s_vid_out_0_1 || ORIG_REF_NAME==fmc_imageon_gs_v_axi4s_vid_out_0_1}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_tc_0_1/fmc_imageon_gs_v_tc_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_tc_0_1 || ORIG_REF_NAME==fmc_imageon_gs_v_tc_0_1}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_rst_processing_system7_0_76M_2/fmc_imageon_gs_rst_processing_system7_0_76M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M_2 || ORIG_REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M_2}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_rst_processing_system7_0_76M1_0/fmc_imageon_gs_rst_processing_system7_0_76M1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M1_0 || ORIG_REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M1_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_onsemi_vita_cam_0_0/fmc_imageon_gs_onsemi_vita_cam_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_onsemi_vita_cam_0_0 || ORIG_REF_NAME==fmc_imageon_gs_onsemi_vita_cam_0_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_onsemi_vita_cam_L_0_0/fmc_imageon_gs_onsemi_vita_cam_L_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_onsemi_vita_cam_L_0_0 || ORIG_REF_NAME==fmc_imageon_gs_onsemi_vita_cam_L_0_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_avnet_hdmi_out_0_0/fmc_imageon_gs_avnet_hdmi_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_avnet_hdmi_out_0_0 || ORIG_REF_NAME==fmc_imageon_gs_avnet_hdmi_out_0_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_avnet_hdmi_out_0_1/fmc_imageon_gs_avnet_hdmi_out_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_avnet_hdmi_out_0_1 || ORIG_REF_NAME==fmc_imageon_gs_avnet_hdmi_out_0_1}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_onsemi_vita_spi_0_0/fmc_imageon_gs_onsemi_vita_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_onsemi_vita_spi_0_0 || ORIG_REF_NAME==fmc_imageon_gs_onsemi_vita_spi_0_0}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_onsemi_vita_spi_0_1/fmc_imageon_gs_onsemi_vita_spi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_onsemi_vita_spi_0_1 || ORIG_REF_NAME==fmc_imageon_gs_onsemi_vita_spi_0_1}]

# IP: bd/fmc_imageon_gs/ip/fmc_imageon_gs_auto_pc_0/fmc_imageon_gs_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_auto_pc_0 || ORIG_REF_NAME==fmc_imageon_gs_auto_pc_0}]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_processing_system7_0_0/fmc_imageon_gs_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_processing_system7_0_0 || ORIG_REF_NAME==fmc_imageon_gs_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_cfa_0_0/fmc_imageon_gs_v_cfa_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_cfa_0_0 || ORIG_REF_NAME==fmc_imageon_gs_v_cfa_0_0}] {/U0 }]/U0 ]]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_cfa_0_0/fmc_imageon_gs_v_cfa_0_0_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_cresample_0_0/fmc_imageon_gs_v_cresample_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_cresample_0_0 || ORIG_REF_NAME==fmc_imageon_gs_v_cresample_0_0}] {/U0 }]/U0 ]]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_cresample_0_0/fmc_imageon_gs_v_cresample_0_0_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_rgb2ycrcb_0_0/fmc_imageon_gs_v_rgb2ycrcb_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==fmc_imageon_gs_v_rgb2ycrcb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_rgb2ycrcb_0_0/fmc_imageon_gs_v_rgb2ycrcb_0_0_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_tc_0_0/fmc_imageon_gs_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_tc_0_0 || ORIG_REF_NAME==fmc_imageon_gs_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_tc_0_0/fmc_imageon_gs_v_tc_0_0_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_fmc_imageon_iic_0_0/fmc_imageon_gs_fmc_imageon_iic_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_fmc_imageon_iic_0_0 || ORIG_REF_NAME==fmc_imageon_gs_fmc_imageon_iic_0_0}]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_fmc_imageon_iic_0_0/fmc_imageon_gs_fmc_imageon_iic_0_0_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_xbar_1/fmc_imageon_gs_xbar_1_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_rst_processing_system7_0_76M_0/fmc_imageon_gs_rst_processing_system7_0_76M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M_0 || ORIG_REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M_0}]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_rst_processing_system7_0_76M_0/fmc_imageon_gs_rst_processing_system7_0_76M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M_0 || ORIG_REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M_0}]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_rst_processing_system7_0_76M_0/fmc_imageon_gs_rst_processing_system7_0_76M_0_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_axi4s_vid_out_0_0/fmc_imageon_gs_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==fmc_imageon_gs_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_axi4s_vid_out_0_0/fmc_imageon_gs_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_vid_in_axi4s_0_0/fmc_imageon_gs_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==fmc_imageon_gs_v_vid_in_axi4s_0_0}] {/inst }]/inst ]]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_vid_in_axi4s_0_0/fmc_imageon_gs_v_vid_in_axi4s_0_0_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_cfa_0_1/fmc_imageon_gs_v_cfa_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_cfa_0_1 || ORIG_REF_NAME==fmc_imageon_gs_v_cfa_0_1}] {/U0 }]/U0 ]]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_cfa_0_1/fmc_imageon_gs_v_cfa_0_1_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_cresample_0_1/fmc_imageon_gs_v_cresample_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_cresample_0_1 || ORIG_REF_NAME==fmc_imageon_gs_v_cresample_0_1}] {/U0 }]/U0 ]]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_cresample_0_1/fmc_imageon_gs_v_cresample_0_1_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_rgb2ycrcb_0_1/fmc_imageon_gs_v_rgb2ycrcb_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_rgb2ycrcb_0_1 || ORIG_REF_NAME==fmc_imageon_gs_v_rgb2ycrcb_0_1}] {/U0 }]/U0 ]]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_rgb2ycrcb_0_1/fmc_imageon_gs_v_rgb2ycrcb_0_1_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_vid_in_axi4s_0_1/fmc_imageon_gs_v_vid_in_axi4s_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_vid_in_axi4s_0_1 || ORIG_REF_NAME==fmc_imageon_gs_v_vid_in_axi4s_0_1}] {/inst }]/inst ]]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_vid_in_axi4s_0_1/fmc_imageon_gs_v_vid_in_axi4s_0_1_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_fmc_imageon_iic_0_1/fmc_imageon_gs_fmc_imageon_iic_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_fmc_imageon_iic_0_1 || ORIG_REF_NAME==fmc_imageon_gs_fmc_imageon_iic_0_1}]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_fmc_imageon_iic_0_1/fmc_imageon_gs_fmc_imageon_iic_0_1_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_axi4s_vid_out_0_1/fmc_imageon_gs_v_axi4s_vid_out_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_axi4s_vid_out_0_1 || ORIG_REF_NAME==fmc_imageon_gs_v_axi4s_vid_out_0_1}] {/inst }]/inst ]]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_axi4s_vid_out_0_1/fmc_imageon_gs_v_axi4s_vid_out_0_1_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_tc_0_1/fmc_imageon_gs_v_tc_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_v_tc_0_1 || ORIG_REF_NAME==fmc_imageon_gs_v_tc_0_1}] {/U0 }]/U0 ]]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_v_tc_0_1/fmc_imageon_gs_v_tc_0_1_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_rst_processing_system7_0_76M_2/fmc_imageon_gs_rst_processing_system7_0_76M_2_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M_2 || ORIG_REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M_2}]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_rst_processing_system7_0_76M_2/fmc_imageon_gs_rst_processing_system7_0_76M_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M_2 || ORIG_REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M_2}]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_rst_processing_system7_0_76M_2/fmc_imageon_gs_rst_processing_system7_0_76M_2_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_rst_processing_system7_0_76M1_0/fmc_imageon_gs_rst_processing_system7_0_76M1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M1_0 || ORIG_REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M1_0}]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_rst_processing_system7_0_76M1_0/fmc_imageon_gs_rst_processing_system7_0_76M1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M1_0 || ORIG_REF_NAME==fmc_imageon_gs_rst_processing_system7_0_76M1_0}]

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_rst_processing_system7_0_76M1_0/fmc_imageon_gs_rst_processing_system7_0_76M1_0_ooc.xdc

# XDC: bd/fmc_imageon_gs/ip/fmc_imageon_gs_auto_pc_0/fmc_imageon_gs_auto_pc_0_ooc.xdc

# XDC: bd/fmc_imageon_gs/fmc_imageon_gs_ooc.xdc
