# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_led/design_led.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led || ORIG_REF_NAME==design_led}]

# IP: bd/design_led/ip/design_led_processing_system7_0_0/design_led_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_processing_system7_0_0 || ORIG_REF_NAME==design_led_processing_system7_0_0}]

# IP: bd/design_led/ip/design_led_axi_gpio_0_0/design_led_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_axi_gpio_0_0 || ORIG_REF_NAME==design_led_axi_gpio_0_0}]

# IP: bd/design_led/ip/design_led_ps7_0_axi_periph_0/design_led_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_led_ps7_0_axi_periph_0}]

# IP: bd/design_led/ip/design_led_rst_ps7_0_50M_0/design_led_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_led_rst_ps7_0_50M_0}]

# IP: bd/design_led/ip/design_led_auto_pc_0/design_led_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_auto_pc_0 || ORIG_REF_NAME==design_led_auto_pc_0}]

# XDC: bd/design_led/design_led_ooc.xdc
