
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.3 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdevcfg.h"

/*
* The configuration table for devices
*/

XDcfg_Config XDcfg_ConfigTable[] =
{
	{
		XPAR_PS7_DEV_CFG_0_DEVICE_ID,
		XPAR_PS7_DEV_CFG_0_BASEADDR
	}
};


