#!/bin/bash -f
# Vivado (TM) v2015.4 (64-bit)
#
# Filename    : fmc_imageon_gs.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Feb 18 19:16:10 +0800 2017
# IP Build 1412160 on Tue Nov 17 13:47:24 MST 2015 
#
# usage: fmc_imageon_gs.sh [-help]
# usage: fmc_imageon_gs.sh [-lib_map_path]
# usage: fmc_imageon_gs.sh [-noclean_files]
# usage: fmc_imageon_gs.sh [-reset_run]
#
# ********************************************************************************************************

# Script info
echo -e "fmc_imageon_gs.sh - Script generated by export_simulation (Vivado v2015.4 (64-bit)-id)\n"

# Script usage
usage()
{
  msg="Usage: fmc_imageon_gs.sh [-help]\n\
Usage: fmc_imageon_gs.sh [-lib_map_path]\n\
Usage: fmc_imageon_gs.sh [-reset_run]\n\
Usage: fmc_imageon_gs.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

if [[ ($# == 1 ) && ($1 != "-lib_map_path" && $1 != "-noclean_files" && $1 != "-reset_run" && $1 != "-help" && $1 != "-h") ]]; then
  echo -e "ERROR: Unknown option specified '$1' (type \"./fmc_imageon_gs.sh -help\" for more information)\n"
  exit 1
fi

if [[ ($1 == "-help" || $1 == "-h") ]]; then
  usage
fi

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./fmc_imageon_gs.sh -help\" for more information)\n"
        exit 1
      fi
      # precompiled simulation library directory path
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
  esac

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Remove generated data from the previous run and re-create setup files/library mappings
reset_run()
{
  files_to_remove=(xelab.pb xsim.jou xvhdl.log xvlog.log compile.log elaborate.log simulate.log xelab.log xsim.log run.log xvhdl.pb xvlog.pb fmc_imageon_gs.wdb xsim.dir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# Main steps
run()
{
  setup $1 $2
  compile
  elaborate
  simulate
}


# RUN_STEP: <compile>
compile()
{
  # Command line options
  opts_ver="-m64 --relax"
  opts_vhd="-m64 --relax"

  # Compile design files
  xvlog $opts_ver -prj vlog.prj 2>&1 | tee compile.log
  xvhdl $opts_vhd -prj vhdl.prj 2>&1 | tee compile.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  xelab --relax --debug typical --mt auto -wto 070d4b0d517547dab9cc3d4462c7bb2e -m64 -L xil_defaultlib -L axi_lite_ipif_v3_0_3 -L v_tc_v6_1_6 -L v_cfa_v7_0_7 -L v_cresample_v4_0_7 -L v_rgb2ycrcb_v7_1_6 -L lib_pkg_v1_0_2 -L lib_cdc_v1_0_2 -L interrupt_control_v3_1_3 -L axi_iic_v2_0_10 -L generic_baseblocks_v2_1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_7 -L fifo_generator_v13_0_1 -L axi_data_fifo_v2_1_6 -L axi_crossbar_v2_1_8 -L proc_sys_reset_v5_0_8 -L v_vid_in_axi4s_v4_0_1 -L v_axi4s_vid_out_v4_0_1 -L axi_protocol_converter_v2_1_7 -L unisims_ver -L unimacro_ver -L secureip --snapshot fmc_imageon_gs xil_defaultlib.fmc_imageon_gs xil_defaultlib.glbl -log elaborate.log
}

# RUN_STEP: <simulate>
simulate()
{
  xsim fmc_imageon_gs -key {Behavioral:sim_1:Functional:fmc_imageon_gs} -tclbatch cmd.tcl -log simulate.log
}
# Script usage
usage()
{
  msg="Usage: fmc_imageon_gs.sh [-help]\n\
Usage: fmc_imageon_gs.sh [-lib_map_path]\n\
Usage: fmc_imageon_gs.sh [-reset_run]\n\
Usage: fmc_imageon_gs.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}


# Launch script
run $1 $2
