# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx_Project/LED_8bits/LED_8bits.srcs/sources_1/bd/led_8bits/ip/led_8bits_axi_gpio_0_0/led_8bits_axi_gpio_0_0.xci
# IP: The module: 'led_8bits_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx_Project/LED_8bits/LED_8bits.srcs/sources_1/bd/led_8bits/ip/led_8bits_axi_gpio_0_0/led_8bits_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_8bits_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Xilinx_Project/LED_8bits/LED_8bits.srcs/sources_1/bd/led_8bits/ip/led_8bits_axi_gpio_0_0/led_8bits_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_8bits_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Xilinx_Project/LED_8bits/LED_8bits.srcs/sources_1/bd/led_8bits/ip/led_8bits_axi_gpio_0_0/led_8bits_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_8bits_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Xilinx_Project/LED_8bits/LED_8bits.srcs/sources_1/bd/led_8bits/ip/led_8bits_axi_gpio_0_0/led_8bits_axi_gpio_0_0.xci
# IP: The module: 'led_8bits_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx_Project/LED_8bits/LED_8bits.srcs/sources_1/bd/led_8bits/ip/led_8bits_axi_gpio_0_0/led_8bits_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_8bits_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Xilinx_Project/LED_8bits/LED_8bits.srcs/sources_1/bd/led_8bits/ip/led_8bits_axi_gpio_0_0/led_8bits_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_8bits_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Xilinx_Project/LED_8bits/LED_8bits.srcs/sources_1/bd/led_8bits/ip/led_8bits_axi_gpio_0_0/led_8bits_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_8bits_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
