# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/led_8bits/led_8bits.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_8bits || ORIG_REF_NAME==led_8bits}]

# IP: bd/led_8bits/ip/led_8bits_processing_system7_0_0/led_8bits_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_8bits_processing_system7_0_0 || ORIG_REF_NAME==led_8bits_processing_system7_0_0}]

# IP: bd/led_8bits/ip/led_8bits_axi_gpio_0_0/led_8bits_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_8bits_axi_gpio_0_0 || ORIG_REF_NAME==led_8bits_axi_gpio_0_0}]

# IP: bd/led_8bits/ip/led_8bits_ps7_0_axi_periph_0/led_8bits_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_8bits_ps7_0_axi_periph_0 || ORIG_REF_NAME==led_8bits_ps7_0_axi_periph_0}]

# IP: bd/led_8bits/ip/led_8bits_rst_ps7_0_50M_0/led_8bits_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_8bits_rst_ps7_0_50M_0 || ORIG_REF_NAME==led_8bits_rst_ps7_0_50M_0}]

# IP: bd/led_8bits/ip/led_8bits_auto_pc_0/led_8bits_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_8bits_auto_pc_0 || ORIG_REF_NAME==led_8bits_auto_pc_0}]

# XDC: bd/led_8bits/led_8bits_ooc.xdc
