// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// CONTROL_BUS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of rows
//        bit 31~0 - rows[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of cols
//        bit 31~0 - cols[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of C_XR0C0
//        bit 31~0 - C_XR0C0[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of C_XR0C1
//        bit 31~0 - C_XR0C1[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of C_XR0C2
//        bit 31~0 - C_XR0C2[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of C_XR1C0
//        bit 31~0 - C_XR1C0[31:0] (Read/Write)
// 0x3c : reserved
// 0x40 : Data signal of C_XR1C1
//        bit 31~0 - C_XR1C1[31:0] (Read/Write)
// 0x44 : reserved
// 0x48 : Data signal of C_XR1C2
//        bit 31~0 - C_XR1C2[31:0] (Read/Write)
// 0x4c : reserved
// 0x50 : Data signal of C_XR2C0
//        bit 31~0 - C_XR2C0[31:0] (Read/Write)
// 0x54 : reserved
// 0x58 : Data signal of C_XR2C1
//        bit 31~0 - C_XR2C1[31:0] (Read/Write)
// 0x5c : reserved
// 0x60 : Data signal of C_XR2C2
//        bit 31~0 - C_XR2C2[31:0] (Read/Write)
// 0x64 : reserved
// 0x68 : Data signal of C_YR0C0
//        bit 31~0 - C_YR0C0[31:0] (Read/Write)
// 0x6c : reserved
// 0x70 : Data signal of C_YR0C1
//        bit 31~0 - C_YR0C1[31:0] (Read/Write)
// 0x74 : reserved
// 0x78 : Data signal of C_YR0C2
//        bit 31~0 - C_YR0C2[31:0] (Read/Write)
// 0x7c : reserved
// 0x80 : Data signal of C_YR1C0
//        bit 31~0 - C_YR1C0[31:0] (Read/Write)
// 0x84 : reserved
// 0x88 : Data signal of C_YR1C1
//        bit 31~0 - C_YR1C1[31:0] (Read/Write)
// 0x8c : reserved
// 0x90 : Data signal of C_YR1C2
//        bit 31~0 - C_YR1C2[31:0] (Read/Write)
// 0x94 : reserved
// 0x98 : Data signal of C_YR2C0
//        bit 31~0 - C_YR2C0[31:0] (Read/Write)
// 0x9c : reserved
// 0xa0 : Data signal of C_YR2C1
//        bit 31~0 - C_YR2C1[31:0] (Read/Write)
// 0xa4 : reserved
// 0xa8 : Data signal of C_YR2C2
//        bit 31~0 - C_YR2C2[31:0] (Read/Write)
// 0xac : reserved
// 0xb0 : Data signal of c_high_thresh
//        bit 31~0 - c_high_thresh[31:0] (Read/Write)
// 0xb4 : reserved
// 0xb8 : Data signal of c_low_thresh
//        bit 31~0 - c_low_thresh[31:0] (Read/Write)
// 0xbc : reserved
// 0xc0 : Data signal of c_invert
//        bit 31~0 - c_invert[31:0] (Read/Write)
// 0xc4 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XIMAGE_FILTER_CONTROL_BUS_ADDR_AP_CTRL            0x00
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_GIE                0x04
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_IER                0x08
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_ISR                0x0c
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_ROWS_DATA          0x10
#define XIMAGE_FILTER_CONTROL_BUS_BITS_ROWS_DATA          32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_COLS_DATA          0x18
#define XIMAGE_FILTER_CONTROL_BUS_BITS_COLS_DATA          32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR0C0_DATA       0x20
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR0C0_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR0C1_DATA       0x28
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR0C1_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR0C2_DATA       0x30
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR0C2_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR1C0_DATA       0x38
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR1C0_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR1C1_DATA       0x40
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR1C1_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR1C2_DATA       0x48
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR1C2_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR2C0_DATA       0x50
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR2C0_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR2C1_DATA       0x58
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR2C1_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_XR2C2_DATA       0x60
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_XR2C2_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR0C0_DATA       0x68
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR0C0_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR0C1_DATA       0x70
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR0C1_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR0C2_DATA       0x78
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR0C2_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR1C0_DATA       0x80
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR1C0_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR1C1_DATA       0x88
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR1C1_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR1C2_DATA       0x90
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR1C2_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR2C0_DATA       0x98
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR2C0_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR2C1_DATA       0xa0
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR2C1_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_YR2C2_DATA       0xa8
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_YR2C2_DATA       32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_HIGH_THRESH_DATA 0xb0
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_HIGH_THRESH_DATA 32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_LOW_THRESH_DATA  0xb8
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_LOW_THRESH_DATA  32
#define XIMAGE_FILTER_CONTROL_BUS_ADDR_C_INVERT_DATA      0xc0
#define XIMAGE_FILTER_CONTROL_BUS_BITS_C_INVERT_DATA      32

